#!/usr/bin/env python
"""Python/Mako static website generator"""

import argparse
import os.path
import sys

from pyder import CommandBase

# These commands are imported so they are detected by CommandBase
from pyder import GenerateCommand
from pyder import ServeCommand

######################################################################

def parse_args(argv):
    """Parse commandline arguments returns args object."""
    parser = argparse.ArgumentParser(
        # print script description with -h/--help
        description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("-d", "--debug",
                        dest="debug", action='store_const', const=True,
                        help="Turn on debugging")

    subparsers = parser.add_subparsers(title="Commands",
                                       description="valid commands")

    CommandBase.add_subparsers(subparsers)

    args = parser.parse_args()
    return args

######################################################################

def main(argv=None):
    # Do argv default this way, as doing it in the functional
    # declaration sets it at compile time.
    if argv is None:
        argv = sys.argv

    args = parse_args(argv)

    CommandBase.show_debug(args.debug)

    cmd = args.command_class(args)
    status = cmd.doit()

    return(status)

if __name__ == "__main__":
    sys.exit(main())
